spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: spring-config-client-dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: prod
  application:
    name: spring-config-client-prod

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/