server:
  port: 8001
mybatis:
  type-aliases-package: com.jin.cloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mapper/*.xml

spring:
  application:
    name: spring-cloud-producer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-producer1

info:
  app.name: spring-cloud-demo
  company.name: jin.com