server:
  port: 9527

spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-zuul
    prefer-ip-address: true

info:
  app.name: spring-cloud-zuul
  company.name: jin.com

zuul:
  routes:
    mydept.serviceId: spring-cloud-producer
    mydept.path: /mydept/**
  ignored-services:
    - spring-cloud-producer
  prefix: /mypath
